---
title: "Pearson's Chi-Squared Test"
author: "KATIE PALOMARES"
output:
  pdf_document:
    toc: yes
    toc_depth: 5
  html_document:
    toc: yes
    toc_depth: '5'
    df_print: paged
---

\newpage


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

library(haven)
library(data.table)
library(magrittr)
library(stats)
library(nnet)
library(lmtest)
library(MASS)
library(ggplot2)
library(googledrive)
library(pedometrics)
library(car)
```

```{r data_prep, results = 'hide', echo = FALSE}


data.directory <- "C:/Users/James/Documents/R/Katies_Thesis/0_Data/"

ifps_dt <- "ifps2.sas7bdat" %>%
           paste0(data.directory, .) %>%
           read_sas() %>%
           as.data.table()


ifps_subset_dt <- ifps_dt[, .(SAMPMIQ)]

####################################################################
#DATA TRANSFORMATIONS
####################################################################
# Breastfeeding difficulties, question 36 --------------------------

N36_cols <- colnames(ifps_dt)[colnames(ifps_dt) %like% "N36"]

N36_dt <- melt(ifps_dt[, .SD, .SDcols = c("SAMPMIQ", N36_cols)], 
                id.vars = "SAMPMIQ", 
                value.name = "response", 
                variable.name = "question")

N36_dt %<>% .[, .(response = sum(response, na.rm = TRUE)), keyby = .(SAMPMIQ)]

N36_dt[, breast_feeding_difficulties := FALSE]
N36_dt[response > 0, breast_feeding_difficulties := TRUE]

ifps_subset_dt[N36_dt, 
        breast_feeding_difficulties := i.breast_feeding_difficulties, 
        on = .(SAMPMIQ)]

rm(N36_dt, N36_cols)

# ----------------------------------------------------------------------

# Breast feeding support, question 38 -----------------------------------

N38_dt <- ifps_dt[, .(N38, SAMPMIQ)]
N38_dt[, breast_feeding_support := FALSE]
N38_dt[N38 == 1, breast_feeding_support := TRUE]

ifps_subset_dt[N38_dt, 
            breast_feeding_support := i.breast_feeding_support, 
            on = .(SAMPMIQ)]

rm(N38_dt)

# ------------------------------------------------------------------------

# Perception of support, question 39

N39_dt <- ifps_dt[, .(N39, SAMPMIQ)]

N39_dt[N39 %in% c(1, 2), perception_of_support := "Unhelfpul"]
N39_dt[N39 %in% c(3), perception_of_support := "Inconclusive"]
N39_dt[N39 %in% c(4, 5), perception_of_support := "Helpful"]

ifps_subset_dt[N39_dt, 
            perception_of_support := i.perception_of_support, 
            on = .(SAMPMIQ)]

rm(N39_dt)

# -----------------------------------------------------------------------

# Breast Feeding Intensity at 2 - 6 months ----------------------------

months <- 1:6

for(i in months){

  if (i == 1) {
    feeding_cols <- colnames(ifps_dt)[colnames(ifps_dt) %like% "N40"]
    
    bf_feeding_col <- "N40A"
  } else {
    feeding_cols <- paste0("M", i, "A1", LETTERS[1:10])
    
    bf_feeding_col <- paste0("M", i, "A1A")
  }

  
  temp_dt <- melt(ifps_dt[, .SD, .SDcols = c("SAMPMIQ", feeding_cols)],
                  id.vars = "SAMPMIQ",
                  value.name = "response",
                  variable.name = "question")
  
  temp_dt[is.na(response) & question == bf_feeding_col, response := 0]
  
  temp_dt %<>% .[, .(breast_feeding_intensity = response[question == bf_feeding_col]/sum(response, 
                                                                                     na.rm = TRUE)), 
                keyby = .(SAMPMIQ)]
  
  temp_dt[is.nan(breast_feeding_intensity), breast_feeding_intensity := NA]
  
  ifps_subset_dt[temp_dt, 
                 breast_feeding_intensity := i.breast_feeding_intensity, 
                 on = .(SAMPMIQ)]
  
  setnames(ifps_subset_dt, 
           "breast_feeding_intensity", 
           paste0("breast_feeding_intensity_", i, "_mo"))
  
  rm(feeding_cols, bf_feeding_col, temp_dt)
}

# ----------------------------------------------------------------------

# BFHI Exposure --------------------------------------------------------

BFHI_dt <- ifps_dt[, .SD, .SDcols = c("N20", 
                                      "N11", 
                                      "N25", 
                                      "N28", 
                                      paste0("N29", c("A", "B", "C")),
                                      "N32", 
                                      "SAMPMIQ")]

number_BFHI_criteria <- 6

# Time until mother breastfed for the first time
BFHI_dt[N20 %in% 1:2, BFHI_exp_1 := TRUE]
BFHI_dt[N20 %in% 3:9, BFHI_exp_1 := FALSE]

# No Pacifiers
BFHI_dt[N11 %in% c(1, 3), BFHI_exp_2 := FALSE]
BFHI_dt[N11 %in% c(2), BFHI_exp_2 := TRUE]

# Rooming in
BFHI_dt[N25 %in% c(1), BFHI_exp_3 := TRUE]
BFHI_dt[N25 %in% c(2, 3), BFHI_exp_3 := FALSE]

# BF on Demand
BFHI_dt[N28 %in% c(1), BFHI_exp_4 := TRUE]
BFHI_dt[N28 %in% c(2, 3), BFHI_exp_4 := FALSE]

# Only BM
BFHI_dt[N29A == 2 & N29B == 2 & N29C == 2, BFHI_exp_5 := TRUE]
BFHI_dt[N29A %in% c(1, 3) | N29B %in% c(1, 3) | N29C %in% c(1, 3), 
        BFHI_exp_5 := FALSE]

# Fostering support groups
BFHI_dt[N32 == 1, BFHI_exp_6 := TRUE]
BFHI_dt[N32 == 2, BFHI_exp_6 := FALSE]

BFHI_dt %<>% melt(., measure.vars = paste0("BFHI_exp_", 1:number_BFHI_criteria),
                  variable.name = "question",
                  value.name = "response")

BFHI_dt %<>% .[, .(BFHI_score = sum(response, na.rm = TRUE),
                   BFHI_all_missing = all(is.na(response))), by = .(SAMPMIQ)]

BFHI_dt[BFHI_all_missing == TRUE, BFHI_score := NA]

ifps_subset_dt[BFHI_dt, BFHI_score := i.BFHI_score, on = .(SAMPMIQ)]

rm(BFHI_dt, number_BFHI_criteria)
# ----------------------------------------------------------------------

# Maternal Age ---------------------------------------------------------
P9_dt <- ifps_dt[, .(P9, SAMPMIQ)]

P9_dt[, unique(P9)] %>% sort()

P9_dt[, maternal_age := cut(P9, 
                            breaks = c(18, 25, 30, 35, Inf), 
                            labels = c("18-24", "25-29", "30-34", "35+"),
                            include.lowest = TRUE,
                            right = FALSE)]

ifps_subset_dt[P9_dt, maternal_age := i.maternal_age, on = .(SAMPMIQ)]

rm(P9_dt)
# ----------------------------------------------------------------------

# Race/Ethnicity -------------------------------------------------------

race_dt <- ifps_dt[, .(RACE_ETH, SAMPMIQ)]

race_dt[RACE_ETH == 1, race_eth := "White, Non-Hispanic"]
race_dt[RACE_ETH == 2, race_eth := "Black, Non-Hispanic"]
race_dt[RACE_ETH == 3, race_eth := "Hispanic"]
race_dt[RACE_ETH %in% c(4, 5), race_eth := "Other"]

ifps_subset_dt[race_dt, race_eth := i.race_eth, on = .(SAMPMIQ)]

rm(race_dt)
# ----------------------------------------------------------------------

# Education ---------------------------------------------
edu_dt <- ifps_dt[, .(EDUC, SAMPMIQ)]

edu_dt[EDUC %in% c(1, 2, 3), education := "Less Than High School"]
edu_dt[EDUC %in% c(4), education := "High School"]
edu_dt[EDUC %in% c(5), education := "1-3 Years College"]
edu_dt[EDUC %in% c(6, 7), education := "College Graduate"]

ifps_subset_dt[edu_dt, education := i.education, on = .(SAMPMIQ)]

rm(edu_dt)
# -------------------------------------------------------

# Parity ------------------------------------------------
parity_dt <- ifps_dt[, .(P41_1, P41_2, SAMPMIQ)]

parity_dt[P41_1 == 0 & P41_2 == 0, parity := "nullipara"]
parity_dt[P41_1 %in% 1:12 | P41_2 %in% 1:12, parity := "primipara"]

ifps_subset_dt[parity_dt, parity := i.parity, on = .(SAMPMIQ)]

parity_dt[, .N, by = .(keyby = P41_1)]
parity_dt[, .N, by = .(keyby = P41_2)]
rm(parity_dt)
# -------------------------------------------------------

# Income Level --------------------------------------------

income_dt <- ifps_dt[, .(INCOME, SAMPMIQ)]

income_dt[INCOME %in% 31:37, income := "<$20,000"]
income_dt[INCOME %in% 38:46, income := "$20,000-$49,999"]
income_dt[INCOME %in% 47:57, income := ">$50,000"]

ifps_subset_dt[income_dt, income := i.income, on = .(SAMPMIQ)]

rm(income_dt)
# ---------------------------------------------------------

# BMI -----------------------------------------------------
bmi_dt <- ifps_dt[, .(P7, P8FT, P8IN, SAMPMIQ)]

bmi_dt[, bmi := (P7/((P8FT * 12 + P8IN)^2)) * 703]

bmi_dt[bmi < 18.5, bmi_class := "Underweight"]
bmi_dt[bmi >= 18.5 & bmi <= 24.9, bmi_class := "Normal Weight"]
bmi_dt[bmi >= 25 & bmi <= 29.9, bmi_class := "Overweight"]
bmi_dt[bmi >= 30, bmi_class := "Obese"]

ifps_subset_dt[bmi_dt, bmi := i.bmi_class, on = .(SAMPMIQ)]

rm(bmi_dt)
# ------------------------------------------------------------

# WIC Participation -------------------------------------------

wic_dt <- ifps_dt[, .(P6_1, P6_2, P6_3, SAMPMIQ)]

wic_dt[P6_1 == 1 | P6_2 == 1, wic_participation := TRUE]
wic_dt[P6_3 == 1, wic_participation := FALSE]

ifps_subset_dt[wic_dt, 
               wic_participation := i.wic_participation, 
               on = .(SAMPMIQ)]


rm(wic_dt)
# ----------------------------------------------------------------------

# Attitude toward breast feeding ----------------------------------

attitude_dt <- ifps_dt[, .(P35E, SAMPMIQ)]

attitude_dt[P35E == 1, breast_feeding_attitude := "Positive"]
attitude_dt[P35E %in% c(2:5), breast_feeding_attitude := "Negative"]

ifps_subset_dt[attitude_dt, 
               breast_feeding_attitude := i.breast_feeding_attitude, 
               on = .(SAMPMIQ)]


rm(attitude_dt)

# -----------------------------------------------------------------

```


```{r modeling, results = 'hide', echo = FALSE}
# Reshaping data before going into modeling
modeling_dt <- melt(ifps_subset_dt, 
                    measure.vars = paste0("breast_feeding_intensity_", 1:6, "_mo"), 
                      variable.name = "time_of_bf_intens_meas", 
                      value.name = "numeric_bf_intensity")

# Setting the boundaries for "low", "medium", and "high" breast feeding intensity
break_options <- c(0, .2, .8, 1)

modeling_dt[, breast_feeding_intensity := cut(numeric_bf_intensity,
                                                 breaks = break_options,
                                                 labels = c("Low", "Medium", "High"),
                                                 include.lowest = TRUE)]

chi_sq_dt <- modeling_dt[!is.na(perception_of_support) &
                          !is.na(breast_feeding_intensity) &
                           perception_of_support != "Inconclusive", .(breast_feeding_intensity,
                                                              perception_of_support,
                                                              time_of_bf_intens_meas)]

chi_sq_dt[, time_of_bf_intens_meas := gsub("breast_feeding_intensity_", "", 
                                             time_of_bf_intens_meas)]
chi_sq_dt[, time_of_bf_intens_meas := paste0(time_of_bf_intens_meas, "nth")]

chi_sq_test_list <- lapply(split(chi_sq_dt, by = "time_of_bf_intens_meas"), function(x){
  temp_table <- table(x$breast_feeding_intensity, x$perception_of_support)

  chi_sq_test <- chisq.test(temp_table)
  
  return(list(contingency_table = temp_table,
              chi_sq_test = chi_sq_test))
})

```

## 1 Month

```{r}
chi_sq_test_list[[1]]
```

## 2 Month

```{r}
chi_sq_test_list[[2]]
```

## 3 Month

```{r}
chi_sq_test_list[[3]]
```

## 4 Month

```{r}
chi_sq_test_list[[4]]
```

## 5 Month

```{r}
chi_sq_test_list[[5]]
```

## 6 Month

```{r}
chi_sq_test_list[[6]]
```
